name: Deploy to development server

on:
  push:
    branches:
      - main

concurrency:
  group: vcci-member-deploy-dev
  cancel-in-progress: true  # üöÄ T·ª± ƒë·ªông h·ªßy job c≈© ƒëang ch·∫°y khi c√≥ push m·ªõi

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and push Docker image

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: twendeesoft/project:vcci-member-be-latest
          build-args: |
            TZ=Asia/Ho_Chi_Minh  # ‚úÖ Thi·∫øt l·∫≠p timezone trong image

  deployment:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy to server

    steps:
      - name: Execute SSH commands on remote server
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: 103.61.123.139
          username: ubuntu
#          key: ${{ secrets.SSH_DEV_PRIVATE_KEY }}
          password: ${{ secrets.SSH_DEV_PASSWORD }}
          port: 22
          script: |
            echo "üîê Logging into Docker..."
            docker login -u ${{ secrets.DOCKER_USERNAME }} --password ${{ secrets.DOCKER_PASSWORD }}
            echo "‚úÖ Docker login successful"
            echo "üöÄ Deploying service..."
            docker compose -f ~/docker-compose/vcci-member-backend/be-dev.yml up -d --build
            echo "üßπ Cleaning up unused images..."
            docker image prune -f
